### ISSUE TITLE
Applying a class to the AutosizeInput does not work.

### ISSUE THREAD

**Issue by bkyf** [houjiazong/vue-autosize-input#2]
Hi, I am having the following:
`
<template>
    <div class="next-to-eachother">
           <AutosizeInput
                type="text"
                 v-model="code"
                 ...
                 v-bind:class="{editableSlot: focused, error: erroneous}"
                 v-bind:id="id"
                 v-bind:key="id"
                 class="input"
             />
           <SomethingElse />
    </div>
</template>
`
However, the class _input_, _editableSlot_ and _error_ are assigned to the div above rather than the AutosizeInput ...

**Comment by houjiazong** [comment]
Please use input-class

**Comment by houjiazong** [comment]
You should use input-class

**Comment by houjiazong** [comment]
#4
